site_name: Hierarchical Configuration
site_url: https://hier_config.readthedocs.io/
repo_url: https://github.com/netdevops/hier_config
theme:
  name: readthedocs

nav:
- Home: index.md
- Install: install.md
- Getting Started: getting-started.md
- Drivers: drivers.md
- Custom Workflows: custom-workflows.md
- Future Config: future-config.md
- JunOS Style Syntax Remediation: junos-style-sytax-remediation.md
- Unified Diff: unified-diff.md
- Working with Tags: tags.md
